import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateTables1764838503534 implements MigrationInterface {
    name = 'CreateTables1764838503534'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "workflow_definitions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "entityType" character varying(50) NOT NULL, "version" integer NOT NULL DEFAULT '1', "isActive" boolean NOT NULL DEFAULT true, "definition" jsonb NOT NULL, "description" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4f92fadfc5fb722f080ceaec272" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."workflow_instances_status_enum" AS ENUM('IN_PROGRESS', 'COMPLETED', 'REJECTED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "workflow_instances" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workflowDefinitionId" uuid NOT NULL, "entityType" character varying(50) NOT NULL, "entityId" uuid NOT NULL, "currentStep" character varying(100), "status" "public"."workflow_instances_status_enum" NOT NULL DEFAULT 'IN_PROGRESS', "startedAt" TIMESTAMP NOT NULL, "completedAt" TIMESTAMP, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_90cc94e44ff8b7b7869f50e4fc4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4b377f691b22b8ae05721074db" ON "workflow_instances" ("workflowDefinitionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3ec8af30ecb4c74d11b9f72586" ON "workflow_instances" ("entityType") `);
        await queryRunner.query(`CREATE INDEX "IDX_61cc8f37480754474e4c46d8a9" ON "workflow_instances" ("entityId") `);
        await queryRunner.query(`CREATE INDEX "IDX_29088385f999b16d6c1503fe29" ON "workflow_instances" ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."workflow_tasks_tasktype_enum" AS ENUM('MANUAL_TASK', 'API_CALL', 'AUTO_TASK')`);
        await queryRunner.query(`CREATE TYPE "public"."workflow_tasks_status_enum" AS ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TYPE "public"."workflow_tasks_priority_enum" AS ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT')`);
        await queryRunner.query(`CREATE TABLE "workflow_tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workflowInstanceId" uuid NOT NULL, "stepId" character varying(100) NOT NULL, "taskName" character varying(200) NOT NULL, "taskType" "public"."workflow_tasks_tasktype_enum" NOT NULL, "assignedTo" uuid, "assignedRole" character varying(50), "status" "public"."workflow_tasks_status_enum" NOT NULL DEFAULT 'PENDING', "priority" "public"."workflow_tasks_priority_enum" NOT NULL DEFAULT 'MEDIUM', "dueDate" TIMESTAMP, "startedAt" TIMESTAMP, "completedAt" TIMESTAMP, "completedBy" uuid, "result" jsonb, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_702a80959e8b659ab50fb64938a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ad3ec6b522a904b04a78a01d69" ON "workflow_tasks" ("workflowInstanceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d1f48dd9dbdc1554a1e3f38e07" ON "workflow_tasks" ("assignedTo") `);
        await queryRunner.query(`CREATE INDEX "IDX_7478656c3e3df08e4564ebca2a" ON "workflow_tasks" ("assignedRole") `);
        await queryRunner.query(`CREATE INDEX "IDX_3d78f23935aed3e3eee4ddf515" ON "workflow_tasks" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_60d8dd9f29ff8cc40120d24d4d" ON "workflow_tasks" ("dueDate") `);
        await queryRunner.query(`CREATE TABLE "workflow_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workflowInstanceId" uuid NOT NULL, "taskId" uuid, "action" character varying(100) NOT NULL, "fromStep" character varying(100), "toStep" character varying(100), "performedBy" uuid, "comments" text, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fea2a8522a65a196224b276dbd9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dfee70cc129f7d3cc04463b067" ON "workflow_history" ("workflowInstanceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_933f82c1297c01dd23cff1b72f" ON "workflow_history" ("performedBy") `);
        await queryRunner.query(`CREATE INDEX "IDX_a78e4c4578db261796f7e073cf" ON "workflow_history" ("createdAt") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "firstName" character varying(100) NOT NULL, "lastName" character varying(100) NOT NULL, "email" character varying(100) NOT NULL, "phoneNumber" character varying(15), "password" character varying NOT NULL, "role" "public"."users_role_enum" NOT NULL DEFAULT 'VIEWER', "status" "public"."users_status_enum" NOT NULL DEFAULT 'PENDING', "isEmailVerified" boolean NOT NULL DEFAULT false, "lastLoginAt" TIMESTAMP, "refreshToken" text, "resetPasswordToken" text, "resetPasswordExpires" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" uuid, "updatedBy" uuid, "deletedAt" TIMESTAMP, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_ace513fa30d485cfd25c11a9e4" ON "users" ("role") `);
        await queryRunner.query(`CREATE INDEX "IDX_3676155292d72c67cd4e090514" ON "users" ("status") `);
        await queryRunner.query(`CREATE TABLE "service_provider_contacts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "serviceProviderId" uuid NOT NULL, "fullName" character varying(200) NOT NULL, "phoneNumber" character varying(15) NOT NULL, "email" character varying(100) NOT NULL, "idNumber" character varying(100), "position" character varying(100), "isPrimary" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_fb4c4efd1489268d5069d248e1" UNIQUE ("serviceProviderId"), CONSTRAINT "PK_b98b0a56dc7a52b008ab248dcb4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "service_provider_bank_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "serviceProviderId" uuid NOT NULL, "bankName" character varying(100) NOT NULL, "accountNumber" character varying(50) NOT NULL, "accountName" character varying(100) NOT NULL, "swiftCode" character varying(20), "branchName" character varying(100), "branchCode" character varying(100), "accountType" character varying(20) NOT NULL DEFAULT 'SAVINGS', "isPrimary" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_18af521483d8ecea9fbc71141e3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a02cd13a328e7dae608420acb8" ON "service_provider_bank_accounts" ("serviceProviderId") `);
        await queryRunner.query(`CREATE TYPE "public"."service_provider_settings_settlementfrequency_enum" AS ENUM('DAILY', 'WEEKLY', 'BIWEEKLY', 'MONTHLY', 'ON_DEMAND')`);
        await queryRunner.query(`CREATE TABLE "service_provider_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "serviceProviderId" uuid NOT NULL, "commissionRate" numeric(5,2) NOT NULL DEFAULT '0', "settlementFrequency" "public"."service_provider_settings_settlementfrequency_enum" NOT NULL DEFAULT 'DAILY', "autoSettlement" boolean NOT NULL DEFAULT true, "minimumSettlementAmount" numeric(15,2) NOT NULL DEFAULT '0', "webhookUrl" text, "webhookEnabled" boolean NOT NULL DEFAULT false, "webhookSecret" character varying(100), "emailNotifications" boolean NOT NULL DEFAULT true, "smsNotifications" boolean NOT NULL DEFAULT true, "pushNotifications" boolean NOT NULL DEFAULT false, "dailyTransactionLimit" numeric(15,2), "dailyTransactionCount" integer, "apiRateLimit" integer NOT NULL DEFAULT '100', "apiEnabled" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_35a276ecb74795785a323d02ef" UNIQUE ("serviceProviderId"), CONSTRAINT "PK_31371d48569b8be3e178e4e40ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."service_providers_businesstype_enum" AS ENUM('SCHOOL', 'HOSPITAL', 'CHURCH', 'SACCO', 'MFI', 'NGO', 'UTILITY', 'GOVERNMENT', 'OTHER')`);
        await queryRunner.query(`CREATE TYPE "public"."service_providers_status_enum" AS ENUM('PENDING', 'UNDER_REVIEW', 'KYC_VERIFICATION', 'APPROVED', 'REJECTED', 'SUSPENDED', 'ACTIVE')`);
        await queryRunner.query(`CREATE TABLE "service_providers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "spCode" character varying(3) NOT NULL, "businessName" character varying(200) NOT NULL, "businessType" "public"."service_providers_businesstype_enum" NOT NULL, "registrationNumber" character varying(100), "tinNumber" character varying(100), "phoneNumber" character varying(15) NOT NULL, "email" character varying(100) NOT NULL, "physicalAddress" text, "region" character varying(100), "district" character varying(100), "nidaVerified" boolean NOT NULL DEFAULT false, "brelaVerified" boolean NOT NULL DEFAULT false, "traVerified" boolean NOT NULL DEFAULT false, "status" "public"."service_providers_status_enum" NOT NULL DEFAULT 'PENDING', "rejectionReason" text, "approvedAt" TIMESTAMP, "approvedBy" uuid, "apiKey" character varying(100), "isActive" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "UQ_2dfa1246cafce52d6bcc64a3bce" UNIQUE ("spCode"), CONSTRAINT "UQ_14d1adea0db135f924c3d017a7c" UNIQUE ("email"), CONSTRAINT "UQ_66b61449d1e23e17729fff2d21f" UNIQUE ("apiKey"), CONSTRAINT "PK_73c86f1298c5285d76e66da2da9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2dfa1246cafce52d6bcc64a3bc" ON "service_providers" ("spCode") `);
        await queryRunner.query(`CREATE INDEX "IDX_14d1adea0db135f924c3d017a7" ON "service_providers" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_fa2e976c2a5469783d62c466c0" ON "service_providers" ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."payment_references_paymentoption_enum" AS ENUM('COMPLETE', 'PARTIAL', 'PRECISE', 'LIMITED', 'PERPETUAL')`);
        await queryRunner.query(`CREATE TYPE "public"."payment_references_status_enum" AS ENUM('ACTIVE', 'USED', 'EXPIRED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "payment_references" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "referenceNumber" character varying(20) NOT NULL, "serviceProviderId" uuid NOT NULL, "customerName" character varying(200) NOT NULL, "customerPhone" character varying(15) NOT NULL, "customerEmail" character varying(100), "customerId" character varying(50), "customerIdType" character varying(20), "customerAccount" character varying(100), "amount" numeric(15,2) NOT NULL, "minPaymentAmount" numeric(15,2), "description" text, "currency" character varying(10) NOT NULL DEFAULT 'TZS', "exchangeRate" numeric(10,4) NOT NULL DEFAULT '1', "paymentOption" "public"."payment_references_paymentoption_enum" NOT NULL DEFAULT 'COMPLETE', "workstation" character varying(50), "issuedBy" character varying(100), "approvedBy" character varying(100), "totalPaid" numeric(15,2) NOT NULL DEFAULT '0', "installmentCount" integer NOT NULL DEFAULT '0', "expiresAt" TIMESTAMP, "status" "public"."payment_references_status_enum" NOT NULL DEFAULT 'ACTIVE', "metadata" jsonb, "usedAt" TIMESTAMP, "transactionId" uuid, "validationAttempts" integer NOT NULL DEFAULT '0', "lastValidatedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_b13a191769818e202a3c4ad4deb" UNIQUE ("referenceNumber"), CONSTRAINT "PK_30d52a35d1c46121bf1d33c20fc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8b37f9431e0b1dd91181fa1d9e" ON "payment_references" ("serviceProviderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e4dbd5c95da410fd7c0a917465" ON "payment_references" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_4ef99f2b4c20896e4d49a56d89" ON "payment_references" ("serviceProviderId", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b13a191769818e202a3c4ad4de" ON "payment_references" ("referenceNumber") `);
        await queryRunner.query(`CREATE TABLE "reference_line_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "referenceId" uuid NOT NULL, "serviceDepartment" character varying(100) NOT NULL, "serviceType" character varying(100) NOT NULL, "serviceReference" character varying(200), "serviceDescription" text, "serviceAmount" numeric(15,2) NOT NULL, "paymentPriority" integer NOT NULL DEFAULT '1', "paidAmount" numeric(15,2) NOT NULL DEFAULT '0', "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_58b9425ce6781dd18eeee5e9fec" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c1a5aa430ba6667c73257ff865" ON "reference_line_items" ("referenceId") `);
        await queryRunner.query(`CREATE TYPE "public"."reference_batches_status_enum" AS ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'PARTIAL')`);
        await queryRunner.query(`CREATE TABLE "reference_batches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "batchId" character varying(100) NOT NULL, "serviceProviderId" uuid NOT NULL, "status" "public"."reference_batches_status_enum" NOT NULL DEFAULT 'PENDING', "totalRequested" integer NOT NULL DEFAULT '0', "successCount" integer NOT NULL DEFAULT '0', "failureCount" integer NOT NULL DEFAULT '0', "processingCount" integer NOT NULL DEFAULT '0', "resultFileUrl" text, "errorMessage" text, "metadata" jsonb, "startedAt" TIMESTAMP, "completedAt" TIMESTAMP, "estimatedCompletionTime" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ebcd9f5a83b32ab439dc7140d54" UNIQUE ("batchId"), CONSTRAINT "PK_764467ad19676876287afe3be10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."settlements_period_enum" AS ENUM('DAILY', 'WEEKLY', 'MONTHLY', 'CUSTOM')`);
        await queryRunner.query(`CREATE TYPE "public"."settlements_status_enum" AS ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'DISPUTED')`);
        await queryRunner.query(`CREATE TABLE "settlements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "settlementNumber" character varying NOT NULL, "serviceProviderId" uuid NOT NULL, "settlementDate" date NOT NULL, "periodStart" date NOT NULL, "periodEnd" date NOT NULL, "period" "public"."settlements_period_enum" NOT NULL DEFAULT 'DAILY', "totalTransactions" integer NOT NULL, "successfulTransactions" integer NOT NULL, "failedTransactions" integer NOT NULL, "totalAmount" numeric(15,2) NOT NULL, "totalFees" numeric(15,2) NOT NULL DEFAULT '0', "netSettlement" numeric(15,2) NOT NULL, "currency" character varying(10) NOT NULL DEFAULT 'TZS', "status" "public"."settlements_status_enum" NOT NULL DEFAULT 'PENDING', "notes" text, "metadata" jsonb, "isReconciled" boolean NOT NULL DEFAULT false, "reconciledAt" TIMESTAMP, "reconciledBy" character varying(200), "reportFileUrl" character varying(500), "reportChecksum" character varying(64), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ff94ecedecc0958f778157e84ce" UNIQUE ("settlementNumber"), CONSTRAINT "PK_5f523ce152b84e818bff9467aab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('SUCCESS', 'FAILED', 'PENDING', 'REVERSED')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "referenceNumber" character varying(20) NOT NULL, "payerName" character varying(200) NOT NULL, "payerPhone" character varying(15) NOT NULL, "amountPaid" numeric(15,2) NOT NULL, "status" "public"."payments_status_enum" NOT NULL DEFAULT 'SUCCESS', "currency" character varying(10) NOT NULL DEFAULT 'TZS', "paymentChannel" character varying(30) NOT NULL DEFAULT 'Bank', "paidAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_32b41cdb985a296213e9a928b5" ON "payments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_b1ccfcfabdda075c2742c0060c" ON "payments" ("referenceNumber") `);
        await queryRunner.query(`CREATE TYPE "public"."cbs_transfers_type_enum" AS ENUM('GL_TO_DEPOSIT', 'DEPOSIT_TO_GL', 'GL_TO_GL', 'DEPOSIT_TO_DEPOSIT')`);
        await queryRunner.query(`CREATE TYPE "public"."cbs_transfers_status_enum" AS ENUM('PENDING', 'SUCCESS', 'FAILED', 'REVERSED')`);
        await queryRunner.query(`CREATE TABLE "cbs_transfers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "paymentId" uuid, "reference" character varying(50) NOT NULL, "creditAccount" character varying(50) NOT NULL, "debitAccount" character varying(50) NOT NULL, "currency" character varying(10) NOT NULL, "amount" numeric(15,2) NOT NULL, "description" text NOT NULL, "type" "public"."cbs_transfers_type_enum" NOT NULL DEFAULT 'GL_TO_DEPOSIT', "status" "public"."cbs_transfers_status_enum" NOT NULL DEFAULT 'PENDING', "cbsResponseCode" text, "cbsResponseMessage" text, "cbsResponse" jsonb, "errorMessage" text, "retryCount" integer NOT NULL DEFAULT '0', "completedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ba4730535151b8771a477b60caa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5c3f1b5da3d31daa4f71a43ef7" ON "cbs_transfers" ("paymentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c3bffd5dac2ed384d8a6fd308a" ON "cbs_transfers" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_5c3f1b5da3d31daa4f71a43ef7" ON "cbs_transfers" ("paymentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c02fef1b5bc5d4e0ba5bc54d5e" ON "cbs_transfers" ("reference") `);
        await queryRunner.query(`ALTER TABLE "workflow_instances" ADD CONSTRAINT "FK_4b377f691b22b8ae05721074dbd" FOREIGN KEY ("workflowDefinitionId") REFERENCES "workflow_definitions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_tasks" ADD CONSTRAINT "FK_ad3ec6b522a904b04a78a01d696" FOREIGN KEY ("workflowInstanceId") REFERENCES "workflow_instances"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_history" ADD CONSTRAINT "FK_dfee70cc129f7d3cc04463b0675" FOREIGN KEY ("workflowInstanceId") REFERENCES "workflow_instances"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_provider_contacts" ADD CONSTRAINT "FK_fb4c4efd1489268d5069d248e17" FOREIGN KEY ("serviceProviderId") REFERENCES "service_providers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_provider_bank_accounts" ADD CONSTRAINT "FK_a02cd13a328e7dae608420acb8c" FOREIGN KEY ("serviceProviderId") REFERENCES "service_providers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_provider_settings" ADD CONSTRAINT "FK_35a276ecb74795785a323d02eff" FOREIGN KEY ("serviceProviderId") REFERENCES "service_providers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_references" ADD CONSTRAINT "FK_8b37f9431e0b1dd91181fa1d9e1" FOREIGN KEY ("serviceProviderId") REFERENCES "service_providers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reference_line_items" ADD CONSTRAINT "FK_c1a5aa430ba6667c73257ff8652" FOREIGN KEY ("referenceId") REFERENCES "payment_references"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reference_batches" ADD CONSTRAINT "FK_27bda3c64ff2df6a3eac55d8a46" FOREIGN KEY ("serviceProviderId") REFERENCES "service_providers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "settlements" ADD CONSTRAINT "FK_fecf82e9dc03f9d794bff4fca4f" FOREIGN KEY ("serviceProviderId") REFERENCES "service_providers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_b1ccfcfabdda075c2742c0060c6" FOREIGN KEY ("referenceNumber") REFERENCES "payment_references"("referenceNumber") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_b1ccfcfabdda075c2742c0060c6"`);
        await queryRunner.query(`ALTER TABLE "settlements" DROP CONSTRAINT "FK_fecf82e9dc03f9d794bff4fca4f"`);
        await queryRunner.query(`ALTER TABLE "reference_batches" DROP CONSTRAINT "FK_27bda3c64ff2df6a3eac55d8a46"`);
        await queryRunner.query(`ALTER TABLE "reference_line_items" DROP CONSTRAINT "FK_c1a5aa430ba6667c73257ff8652"`);
        await queryRunner.query(`ALTER TABLE "payment_references" DROP CONSTRAINT "FK_8b37f9431e0b1dd91181fa1d9e1"`);
        await queryRunner.query(`ALTER TABLE "service_provider_settings" DROP CONSTRAINT "FK_35a276ecb74795785a323d02eff"`);
        await queryRunner.query(`ALTER TABLE "service_provider_bank_accounts" DROP CONSTRAINT "FK_a02cd13a328e7dae608420acb8c"`);
        await queryRunner.query(`ALTER TABLE "service_provider_contacts" DROP CONSTRAINT "FK_fb4c4efd1489268d5069d248e17"`);
        await queryRunner.query(`ALTER TABLE "workflow_history" DROP CONSTRAINT "FK_dfee70cc129f7d3cc04463b0675"`);
        await queryRunner.query(`ALTER TABLE "workflow_tasks" DROP CONSTRAINT "FK_ad3ec6b522a904b04a78a01d696"`);
        await queryRunner.query(`ALTER TABLE "workflow_instances" DROP CONSTRAINT "FK_4b377f691b22b8ae05721074dbd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c02fef1b5bc5d4e0ba5bc54d5e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5c3f1b5da3d31daa4f71a43ef7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c3bffd5dac2ed384d8a6fd308a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5c3f1b5da3d31daa4f71a43ef7"`);
        await queryRunner.query(`DROP TABLE "cbs_transfers"`);
        await queryRunner.query(`DROP TYPE "public"."cbs_transfers_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."cbs_transfers_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b1ccfcfabdda075c2742c0060c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32b41cdb985a296213e9a928b5"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP TABLE "settlements"`);
        await queryRunner.query(`DROP TYPE "public"."settlements_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."settlements_period_enum"`);
        await queryRunner.query(`DROP TABLE "reference_batches"`);
        await queryRunner.query(`DROP TYPE "public"."reference_batches_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c1a5aa430ba6667c73257ff865"`);
        await queryRunner.query(`DROP TABLE "reference_line_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b13a191769818e202a3c4ad4de"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4ef99f2b4c20896e4d49a56d89"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e4dbd5c95da410fd7c0a917465"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b37f9431e0b1dd91181fa1d9e"`);
        await queryRunner.query(`DROP TABLE "payment_references"`);
        await queryRunner.query(`DROP TYPE "public"."payment_references_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payment_references_paymentoption_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fa2e976c2a5469783d62c466c0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_14d1adea0db135f924c3d017a7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2dfa1246cafce52d6bcc64a3bc"`);
        await queryRunner.query(`DROP TABLE "service_providers"`);
        await queryRunner.query(`DROP TYPE "public"."service_providers_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."service_providers_businesstype_enum"`);
        await queryRunner.query(`DROP TABLE "service_provider_settings"`);
        await queryRunner.query(`DROP TYPE "public"."service_provider_settings_settlementfrequency_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a02cd13a328e7dae608420acb8"`);
        await queryRunner.query(`DROP TABLE "service_provider_bank_accounts"`);
        await queryRunner.query(`DROP TABLE "service_provider_contacts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3676155292d72c67cd4e090514"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ace513fa30d485cfd25c11a9e4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a78e4c4578db261796f7e073cf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_933f82c1297c01dd23cff1b72f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dfee70cc129f7d3cc04463b067"`);
        await queryRunner.query(`DROP TABLE "workflow_history"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_60d8dd9f29ff8cc40120d24d4d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d78f23935aed3e3eee4ddf515"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7478656c3e3df08e4564ebca2a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d1f48dd9dbdc1554a1e3f38e07"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad3ec6b522a904b04a78a01d69"`);
        await queryRunner.query(`DROP TABLE "workflow_tasks"`);
        await queryRunner.query(`DROP TYPE "public"."workflow_tasks_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."workflow_tasks_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."workflow_tasks_tasktype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_29088385f999b16d6c1503fe29"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_61cc8f37480754474e4c46d8a9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ec8af30ecb4c74d11b9f72586"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4b377f691b22b8ae05721074db"`);
        await queryRunner.query(`DROP TABLE "workflow_instances"`);
        await queryRunner.query(`DROP TYPE "public"."workflow_instances_status_enum"`);
        await queryRunner.query(`DROP TABLE "workflow_definitions"`);
    }

}
